apply plugin: 'com.android.application'

ext {
    appBinaryName = "toyvpn"
}

android {
    compileSdkVersion 31
    buildToolsVersion "31.0.0"
    ndkVersion = '23.1.7779620'

    defaultConfig {
        applicationId "net.cachefiles.toyvpn"
        minSdkVersion 26
        targetSdkVersion 31
        versionName = '0.1.1'
    }

    dependencies {
	def preference_version = "1.2.1"
	implementation "androidx.preference:preference-ktx:$preference_version"
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            jniDebuggable true
            renderscriptDebuggable true
            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "${appBinaryName}_${variant.buildType.name}_${defaultConfig.versionName}.apk"
                }
            }
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "${appBinaryName}_${variant.buildType.name}_${defaultConfig.versionName}.apk"
                }
            }
        }
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
